import { z } from 'zod';

// imageBase64 / imageMimeType are NOT generated by the LLM —
// they are injected server-side from the uploaded figure after the vision call.
export const FigureBasedSchema = z.object({
  marks:         z.number().positive(),
  imageBase64:   z.string().optional(),
  imageMimeType: z.enum(['image/jpeg', 'image/png', 'image/webp', 'image/gif']).optional(),
  questionText:  z.string().min(1),
  subType:       z.enum(['mcq', 'shortAnswer']).default('mcq'),
  options:       z.array(z.string().min(1)).min(2).max(6).optional(),
  correctAnswer: z.string().min(1),
  useLatex:      z.boolean().default(false),
  explanation:   z.string().min(1),
});
